apiVersion: v1
kind: Service
metadata:
  name: web-demo
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: web-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
  namespace: default
  labels:
    name: web-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
      - name: web-demo
        image: web-demo:v1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        env:
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: ASPNETCORE_PATHBASE
          value: "/web"
        - name: ASPNETCORE_PROXYBEHAVIOR
          value: "RemoveProxyPath" # values: NoProxy|MaintainProxyPath|RemoveProxyPath
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /web(/|$)(.*)
        backend:
          serviceName: web-demo
          servicePort: 80
