apiVersion: v1
kind: Service
metadata:
  name: resources-demo
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 8080
  selector:
    app: resources-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-demo
  namespace: default
  labels:
    name: resources-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resources-demo
  template:
    metadata:
      labels:
        app: resources-demo
    spec:
      containers:
      - name: resources-demo
        image: gcr.io/kuar-demo/kuard-amd64:blue
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "1Gi"
            cpu: "1"
        ports:
          - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: resources-demo
          servicePort: 8080
