apiVersion: v1
kind: Service
metadata:
  name: web-demo
  namespace: default
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: web-demo
---
kind: ConfigMap 
apiVersion: v1 
metadata:
  name: web-demo
data:
  AppConfiguration__FavoriteMountain: Balaitus (from config map)
---
apiVersion: v1
kind: Secret
metadata:
  name: web-demo
type: Opaque
stringData:
  AppConfiguration__City: Huesca (from secret)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-demo
  namespace: default
  labels:
    name: web-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web-demo
    spec:
      containers:
      - name: web-demo
        image: web-demo:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "400Mi"
            cpu: "1"
        ports:
          - containerPort: 80
        envFrom:
        - configMapRef:
            name: web-demo
        - secretRef:
            name: web-demo
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-demo
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /
        backend:
          serviceName: web-demo
          servicePort: 80
